package MTalk;


/**
* MTalk/PeerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* mardi 4 janvier 2011 17 h 51 CET
*/

public interface PeerOperations 
{
  String getInformations ();

  /**
  		 * @param numConvSideA : le numéro que l'appelant donne à la conversation vue de son c�}té.
  		 * @param subject : sujet de la conversation
  		 * @param myInformations : informations de l'appelant (username ou autre)
  		 * @param mytalkIor : Ior du talk que l'appelant crée pour la conversation (de son c�}té donc)
  		 **/
  void requestTalk (short numConvSideA, String subject, String myInformations, String mytalkIor);
} // interface PeerOperations
