package MTalk;


/**
* MTalk/TalkHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* mardi 4 janvier 2011 17 h 51 CET
*/

abstract public class TalkHelper
{
  private static String  _id = "IDL:MTalk/Talk:1.0";

  public static void insert (org.omg.CORBA.Any a, MTalk.Talk that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MTalk.Talk extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MTalk.TalkHelper.id (), "Talk");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MTalk.Talk read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_TalkStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MTalk.Talk value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MTalk.Talk narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MTalk.Talk)
      return (MTalk.Talk)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MTalk._TalkStub stub = new MTalk._TalkStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MTalk.Talk unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MTalk.Talk)
      return (MTalk.Talk)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MTalk._TalkStub stub = new MTalk._TalkStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
