package MTalk;

/**
* MTalk/TalkHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from talk.idl
* mardi 4 janvier 2011 17 h 51 CET
*/

public final class TalkHolder implements org.omg.CORBA.portable.Streamable
{
  public MTalk.Talk value = null;

  public TalkHolder ()
  {
  }

  public TalkHolder (MTalk.Talk initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MTalk.TalkHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MTalk.TalkHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MTalk.TalkHelper.type ();
  }

}
